### ISSUE TITLE
When will the audio feature extraction code be released?

### ISSUE THREAD

**Issue by Franklin905** [GeWu-Lab/Generalizable-Audio-Visual-Segmentation#1]
Great work and thank you for sharing the code!

I extracted the audio feature of the video '--iSerV5DbY_68000_78000' using the official VGGish model, but the output feature did not match the one provided in 'GAVS/segment_anything/feature_extract/v2_vggish_embs/--iSerV5DbY_68000_78000.npy'.
Also, I encountered 'EOFError: No data left in file' when loading '--iSerV5DbY_119000_129000.npy'.
I would like to know when the audio feature extraction will be released.

Thank you!

**Comment by yaotingwangofficial** [comment]
Hi Franklin905, thanks for your interest.

I have updated the instruction in README for audio feature extraction.
Please note that these .npy feature files are kind of 'placeholders', just providing a better understanding of the code framework.
