### ISSUE TITLE
Asking for the model checkpoint

### ISSUE THREAD

**Issue by beandkay** [GeWu-Lab/Generalizable-Audio-Visual-Segmentation#3]
Hi,
Thank you for your work.
I clone your repo and ran the training for V1M dataset.
However, I only got 0.46597322821617126/0.6202007253741613 for IoU/F-score.
It is quite much lower than the results you reported on the paper.
Can you please clarify this?

**Comment by yaotingwangofficial** [comment]
Hi, please make sure you open the visual backbone with adapter for tuning. Last six layers should be enough. If you not sure, you can print out the trainable parameters' name here.

Check [config](https://github.com/GeWu-Lab/Generalizable-Audio-Visual-Segmentation/blob/main/GAVS/segment_anything/config.py): --tune_v

wth corresponding code line 69 of the [model file](https://github.com/GeWu-Lab/Generalizable-Audio-Visual-Segmentation/blob/main/GAVS/avs_model.py).
