### ISSUE TITLE
关于计算资源的需求

### ISSUE THREAD

**Issue by Yuzuriha-Inori-x** [GeWu-Lab/Generalizable-Audio-Visual-Segmentation#4]
你好！请问，这个代码运行的最低计算资源是多少呢？

**Comment by yaotingwangofficial** [comment]
您好, 3090 24G * 1即可, 但是相应的SAM的visual encoder的mlp adapter层数会受到限制.

**Comment by yaotingwangofficial** [comment]
您好, 3090 24G * 1即可, 但是相应的SAM的visual encoder的mlp adapter层数会受到限制.
