### ISSUE TITLE
Reproducing published results and results based on different ViT backbones

### ISSUE THREAD

**Issue by abdurad** [GeWu-Lab/Generalizable-Audio-Visual-Segmentation#5]
I am facing difficulty replicating the published results with the ViT-B backbone; the performance is significantly lower than reported. Additionally, tuning Tuve-V has not yielded any improvements. I am also curious if you have experimented with ViT-L and ViT-H and could share the results. My experiments based on ViT-L and ViT-H also produced results below those reported in the paper for ViT-B.

**Comment by yaotingwangofficial** [comment]
Hi, could you please check your config:
(1) Check [config](https://github.com/GeWu-Lab/Generalizable-Audio-Visual-Segmentation/blob/main/GAVS/segment_anything/config.py): --tune_v  , wth corresponding code line 69 of the [model file](https://github.com/GeWu-Lab/Generalizable-Audio-Visual-Segmentation/blob/main/GAVS/avs_model.py).
(2) Check whether the "adapter" is enabled (THIS IS IMPORTANT): [https://github.com/GeWu-Lab/Generalizable-Audio-Visual-Segmentation/blob/main/GAVS/segment_anything/modeling/transformer.py#L179](url)  - please print out and check the trainable params names.  tune_v is about adapter tuning for the visual encoder while adapter_tf is about two-layer attention, it should be caused improvements when you tuning for downstream tasks like segmentation.

---
We did not try large or huge version as they require more computation.

**Comment by abdurad** [comment]
Thank you for prompt response. Here are thetrainable parameters:

##################################################
Requires_grad: model_v.image_encoder.blocks.6.adapter_v.0.weight
Requires_grad: model_v.image_encoder.blocks.6.adapter_v.0.bias
Requires_grad: model_v.image_encoder.blocks.6.adapter_v.2.weight
Requires_grad: model_v.image_encoder.blocks.6.adapter_v.2.bias
Requires_grad: model_v.image_encoder.blocks.7.norm1.weight
Requires_grad: model_v.image_encoder.blocks.7.norm1.bias
Requires_grad: model_v.image_encoder.blocks.7.norm2.weight
Requires_grad: model_v.image_encoder.blocks.7.norm2.bias
Requires_grad: model_v.image_encoder.blocks.7.adapter_v.0.weight
Requires_grad: model_v.image_encoder.blocks.7.adapter_v.0.bias
Requires_grad: model_v.image_encoder.blocks.7.adapter_v.2.weight
Requires_grad: model_v.image_encoder.blocks.7.adapter_v.2.bias
Requires_grad: model_v.image_encoder.blocks.8.norm1.weight
Requires_grad: model_v.image_encoder.blocks.8.norm1.bias
Requires_grad: model_v.image_encoder.blocks.8.norm2.weight
Requires_grad: model_v.image_encoder.blocks.8.norm2.bias
Requires_grad: model_v.image_encoder.blocks.8.adapter_v.0.weight
Requires_grad: model_v.image_encoder.blocks.8.adapter_v.0.bias
Requires_grad: model_v.image_encoder.blocks.8.adapter_v.2.weight
Requires_grad: model_v.image_encoder.blocks.8.adapter_v.2.bias
Requires_grad: model_v.image_encoder.blocks.9.norm1.weight
Requires_grad: model_v.image_encoder.blocks.9.norm1.bias
Requires_grad: model_v.image_encoder.blocks.9.norm2.weight
Requires_grad: model_v.image_encoder.blocks.9.norm2.bias
Requires_grad: model_v.image_encoder.blocks.9.adapter_v.0.weight
Requires_grad: model_v.image_encoder.blocks.9.adapter_v.0.bias
Requires_grad: model_v.image_encoder.blocks.9.adapter_v.2.weight
Requires_grad: model_v.image_encoder.blocks.9.adapter_v.2.bias
Requires_grad: model_v.image_encoder.blocks.10.norm1.weight
Requires_grad: model_v.image_encoder.blocks.10.norm1.bias
Requires_grad: model_v.image_encoder.blocks.10.norm2.weight
Requires_grad: model_v.image_encoder.blocks.10.norm2.bias
Requires_grad: model_v.image_encoder.blocks.10.adapter_v.0.weight
Requires_grad: model_v.image_encoder.blocks.10.adapter_v.0.bias
Requires_grad: model_v.image_encoder.blocks.10.adapter_v.2.weight
Requires_grad: model_v.image_encoder.blocks.10.adapter_v.2.bias
Requires_grad: model_v.image_encoder.blocks.11.norm1.weight
Requires_grad: model_v.image_encoder.blocks.11.norm1.bias
Requires_grad: model_v.image_encoder.blocks.11.norm2.weight
Requires_grad: model_v.image_encoder.blocks.11.norm2.bias
Requires_grad: model_v.image_encoder.blocks.11.adapter_v.0.weight
Requires_grad: model_v.image_encoder.blocks.11.adapter_v.0.bias
Requires_grad: model_v.image_encoder.blocks.11.adapter_v.2.weight
Requires_grad: model_v.image_encoder.blocks.11.adapter_v.2.bias
Requires_grad: model_v.mask_decoder.transformer.layers.0.adapter_tf.dense.weight
Requires_grad: model_v.mask_decoder.transformer.layers.0.adapter_tf.dense.bias
Requires_grad: model_v.mask_decoder.transformer.layers.0.adapter_tf.proj.weight
Requires_grad: model_v.mask_decoder.transformer.layers.0.adapter_tf.proj.bias
Requires_grad: model_v.mask_decoder.transformer.layers.1.adapter_tf.dense.weight
Requires_grad: model_v.mask_decoder.transformer.layers.1.adapter_tf.dense.bias
Requires_grad: model_v.mask_decoder.transformer.layers.1.adapter_tf.proj.weight
Requires_grad: model_v.mask_decoder.transformer.layers.1.adapter_tf.proj.bias
Requires_grad: model_v.mask_decoder.audio_proj.0.weight
Requires_grad: model_v.mask_decoder.audio_proj.0.bias
Requires_grad: model_v.mask_decoder.audio_proj.2.weight
Requires_grad: model_v.mask_decoder.audio_proj.2.bias

**Comment by abdurad** [comment]
I also confirmed that the tune_v parameter is also less than 12. I tested both values, 9 and 6, and the best results I achieved were an mIoU of 0.5439 and an F-score of 0.7182.

**Comment by yaotingwangofficial** [comment]
Many thanks for providing the params names, it should be fine in my view. I will check the model and code then. But I'm in another institution and I expect to give you response before 16 Sep, many thanks for your understanding

**Comment by yaotingwangofficial** [comment]
Hi abdurad, I have tried to download the dataset again and I can see the dataset format has been changed, and I did not check more details, I need time to modify the code however and check whether there are missing during the code reorganization. 

Currently my suggestion is instead of tuning from the 6 or 9 layer,  tuning the visual encoder with huggingface lora from the head layer which may generate better results for a fair comparison with those methods with visual encoder tuning, or, just disable the visual encoder tuning to compare with those method with frozen backbond. For visual encoder tuning or frozen, please check the comment "# visual adapter tuning" in GAVS/segment_anything/modeling/image_encoder.py, you can delete them if you want to use lora.

**Comment by abdurad** [comment]
Thank you.
